theme: "hugo-PaperMod"
baseURL: https://xpblog.netlify.app/
languageCode: en-us
DefaultContentLanguage: zh-cn
title: Guanxxxxxp

enableInlineShortcodes: true #允许内联短码
enableEmoji: true # 允许使用 Emoji 表情，建议 true
enableRobotsTXT: true # 允许爬虫抓取到搜索引擎，建议 true

hasCJKLanguage: true # 自动检测是否包含 中文日文韩文 如果文章中使用了很多中文引号的话可以开启

buildDrafts: false
buildFuture: false
buildExpired: false

#googleAnalytics:UA-123-45 # 谷歌统计
# Copyright: Sulv

paginate: 10    # 每页显示的文章数

ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]

minify:
    disableXML: true
    # minifyOutput: true

permalinks: #浏览器链接显示方式
  post: "/:title/"
  # post: "/:year/:month/:day/:title/"

defaultContentLanguage: en # 最顶部首先展示的语言页面
defaultContentLanguageInSubdir: true

languages:
    en:
      languageName: "English"
      # contentDir: content/english
      weight: 1
      profileMode:
        enabled: true
        title: (〃'▽'〃)
        subtitle: "🧨希望能在这找到点好玩的<br/>👏🏼欢迎光临霄鹏(Guanxxxxxp)的博客<br/>👇联系方式"
        imageUrl: "img/Q.png" #图片放在static/img/Q.png
        imageTitle: "叮~~"
        imageWidth: 150
        imageHeight: 150
        buttons:
          - name: 📝杂记
            url: post/blog
          - name: 👨🏻‍💻技术
            url: post/tech
          - name: 📕阅读
            url: post/read

      menu:
        main:
          - identifier: search
            name: 🔍搜索
            url: search
            weight: 1
          - identifier: home
            name: 🏠主页
            url: /
            weight: 2
          - identifier: posts
            name: 📚文章
            url: post
            weight: 3
          - identifier: archives
            name: ⏱时间轴
            url: archives/
            weight: 20
          - identifier: tags
            name: 🔖标签
            url: tags
            weight: 40
          - identifier: about
            name: 🙋🏻‍♂️关于
            url: about
            weight: 50
          - identifier: links
            name: 🤝友链
            url: links
            weight: 60
            
outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    # description: "这是一个纯粹的博客......"
    author: Guanxxxxxp
    # author: ["Me", "You"] # multiple authors
    defaultTheme: auto  # defaultTheme: light or  dark 
    disableThemeToggle: false
    DateFormat: "2006-01-02"
    ShowShareButtons: true
    ShowReadingTime: true
    # disableSpecialistPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    hideFooter: false # 隐藏页脚
    ShowWordCounts: true
    VisitCount: true
    ShowFullTestinRSS: true
    page_view_conter: true # 统计字数
    ShowStatInSectionTermList: false
    ShowStatInArchive: false
    
    ShowLastMod: true #显示文章更新时间

    ShowToc: true # 显示目录
    TocOpen: true # 自动展开目录

    socialIcons:
        - name: github
          url: "https://github.com/Guanxxxxxp"
        - name: QQ
          url: "img/qq.png"
        - name: WeChat
          url: "img/wechat.jpg"
        - name: email
          url: "mailto: 3093387729@qq.com"
        - name: bilibili
          url: "https://space.bilibili.com/470463231?spm_id_from=333.1007.0.0"
        - name: RSS
          url: "index.xml"
    label:
        text: "Guanxxxxxp"
        icon: "img/T.png"
        iconHeight: 35
        
    assets:
        favicon: "img/Q.png"
        favicon16x16: "img/Q.png"
        favicon32x32: "img/Q.png"
        apple_touch_icon: "Q.png"
        safari_pinned_tab: "Q.png"
        
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 1
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary"]
        
    comments: true
    
    twikoo:
      version: 1.6.7

taxonomies:
    category: categories
    tag: tags
    series: series

markup:
    goldmark:
        renderer:
            unsafe: true # HUGO 默认转义 Markdown 文件中的 HTML 代码，如需开启的话
    highlight:
        # anchorLineNos: true
        codeFences: true  
        guessSyntax: true
        lineNos: true
        # noClasses: false
        # style: monokai
        style: darcula

        # codeFences：代码围栏功能，这个功能一般都要设为 true 的，不然很难看，就是干巴巴的-代码文字，没有颜色。
        # guessSyntax：猜测语法，这个功能建议设置为 true, 如果你没有设置要显示的语言则会自动匹配。
        # hl_Lines：高亮的行号，一般这个不设置，因为每个代码块我们可能希望让高亮的地方不一样。
        # lineNoStart：行号从编号几开始，一般从 1 开始。
        # lineNos：是否显示行号，我比较喜欢显示，所以我设置的为 true.
        # lineNumbersInTable：使用表来格式化行号和代码,而不是 标签。这个属性一般设置为 true.
        # noClasses：使用 class 标签，而不是内嵌的内联样式

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
